= Perfective Build for TypeScript

The `@perfective/build` package provides base configurations
and presets for tools like Gulp, TypeScript, Babel, etc.
to reduce code duplication between projects setup.


== Installation

[source,shell script]
----
npm install --save-dev \
    @perfective/build \
    gulp \
    typescript
----


== Building a TypeScript project

. Check that `devDependencies` contain correct versions of `gulp` and `typescript`:
+
[source,json]
----
{
    "devDependencies": {
        "gulp": "^4.0.2",
        "typescript": "^4.3.4"
    }
}
----
+
. Setup `tsconfig.json` using the base `tsconfig.strict.json` configuration.
+
[source,json]
----
{
    "extends": "@perfective/build/tsconfig.strict.json",
    "compilerOptions": {
        "rootDir": "./src"
    },
    "exclude": [
        "dist"
    ]
}
----
+
. Add the `RequireExtension` plugin to your `babel.config.js`.
This plugin replaces `.js` extensions with the `.cjs` extensions in the NodeJS `require()` statements.
+
[source,javascript]
----
const perfective = require('@perfective/build/babel');

module.exports = {
    presets: [],
    plugins: [
        perfective.babelPluginRequireExtension
    ]
};
----


== Setup Prettier

. Add `prettier` as a dev dependency:
+
[source,json]
----
{
    "devDependencies": {
        "prettier": "^2.3.1"
    }
}
----
+
. Setup `.prettierrc.js`:
+
[source,js]
----
const perfective = require('@perfective/build/prettier');

module.exports = perfective;
----
+
. Setup `.prettierignore`:
+
[source,ignore]
----
# Build
dist

# ESLint
*.js
*.jsx
*.ts
*.tsx
----
+
. Update `package.json` scripts.
+
[source,json]
----
{
    "scripts": {
        "lint": "npm run lint:prettier",
        "lint:prettier": "prettier --write .",
        "lint:prettier:build": "prettier --check ."
    }
}
----
+
Use `lint:prettier` during development (to fix code automatically)
and `lint:prettier:build` to verify the build (to fail if code is not formatted).


== Setup Jest

. Add `jest` and related peer dependencies as dev dependencies:
+
[source,json]
----
{
    "deDependencies": {
        "jest": "^27.0.4",
        "ts-jest": "^27.0.2"
    }
}
----
+
. Setup `jest.config.js`:
+
[source,js]
----
const perfective = require('@perfective/build/jest');

module.exports = perfective;
----
+
. Update `package.json` scripts:
+
[source,json]
----
{
    "scripts": {
        "test": "jest",
        "test:build": "jest --clearCache && jest --collectCoverage"
    }
}
----
+
Use `test` for development testing
and `test:build` to test during the build (and fail if test coverage is not sufficient).
